- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wordpress
    name: wordpress
  spec:
    ports:
    - port: 80
    selector:
      app: wordpress
      tier: frontend
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: wordpress
    name: wordpress
  spec:
    selector:
      matchLabels:
        app: wordpress
        tier: frontend
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: wordpress
          tier: frontend
      spec:
        containers:
        - env:
          - name: WORDPRESS_DB_HOST
            value: devopsinterview.cw7qgk28g9tl.us-east-1.rds.amazonaws.com
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: rds-pass
          - name: WORDPRESS_DB_NAME
            value: devopsinterview
          - name: WORDPRESS_DB_USER
            value: devopsinterview
          image: gcr.io/wordpress:5.5-latest
          name: wordpress
          ports:
          - containerPort: 80
            name: wordpress
